---
name: shell commands
on: [push] 	##event to triger the workflow
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
     - name: echo a string
       run: echo "hello-world"
     - name: multiline script
       run:  |
         echo "multiline script"
         hostname
