---
name: shell commands
on: [push] 	##event to triger the workflow
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
     - name: echo a string
       run: echo "hello-world"
     - name: multiline script
       run:  |
         echo "multiline script"
         hostname
     - name: phthon command
       run: |
         import platform
         print(platform.processor())
       shell: python  
